FROM ubuntu:22.04


RUN apt-get update \
    && apt-get install -y keychain \
    && apt-get install -y libpam-ssh \
    && apt-get install -y monkeysphere \
    && apt-get install -y ssh-askpass \
    && apt-get install -y openssh-client


# Comando para que no se cierre el contenedor
CMD ["sleep", "infinity"]